<?php

namespace app\admin\common;

use app\admin\model\System;
use  think\Controller;
use think\Request;
use think\Session;

class Base extends Controller
{

	protected function _initialize()
	{
		parent::_initialize(); // TODO: Change the autogenerated stub

		//在公交控制器的初始化中，创建一个变量来判断用户是否登录或者退出
		define('USER_ID', Session::get('user_id'));
		//获取网站配置信息
		$config = $this->getSystem();
		//获取当前请求对象
		$request = Request::instance();

		//查询一下当前网站开关状态
		$this->getStatus($request, $config);
	}

	protected function isLogin()
	{
		if (is_null(USER_ID)) {
			$this->error('未登录，无权访问', 'login/index');
		}
	}

	protected function alreadyLogin()
	{
		if (!is_null(USER_ID)) {
			$this->error('请不要重复登录', 'index/index');
		}
	}

	public function getSystem()
	{
		return System::get(1);
	}

	public function getStatus($request, $config)
	{
		if ($request->module() !== 'admin') {
			if ($config->is_close == 1) {
				$this->error("网站已关闭");
				exit;
			}
		}
	}
}